apiVersion: v1
kind: Service
metadata:
  name: healthcare-app-service
  namespace: healthcare-system
spec:
  selector:
    app: healthcare-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
